### ISSUE TITLE
Live Update not working on El Capitan

### ISSUE THREAD

**Issue by Castronova** [euclio/vim-markdown-composer#9] opened 2016-01-29 17:17 UTC
When I open a markdown file, Safari open and displays the text properly.  However, when edits are made to the markdown text, the browser preview does not update.  Also, it won't update even when the browser page is manually refreshed.  The only way that I have been able to refresh the bowser text is to reopen the markdown file in neovim.

**Comment by euclio** [comment] 2016-01-29 17:43
Are there any errors in the JavaScript console?

**Comment by euclio** [comment] 2016-04-04 23:17
Closing this as I cannot reproduce.

**Comment by theamazingfedex** [comment] 2016-04-05 16:17
Hmm, I seem to be having a similar, if not the same issue. I get no errors in either the chrome console, or in vim messages, and in order to update the markdown, I must exit and restart vim to re-launch the server.
The only lines in my .vimrc that pertain to markdown-composer are:
``` vim
   let g:markdown_composer_syntax_theme='monokai'
   let g:markdown_fenced_languages = ['html', 'javascript', 'vim', 'python', 'bash=sh']
```

**Comment by theamazingfedex** [comment] 2016-04-05 16:28
Weird, shortly after I commented that, it started working. It seems to just take a long time to start updating the webpage at first; after I forgot about it for 20 minutes, it worked.

**Comment by euclio** [comment] 2016-04-05 17:11
Interesting. I wonder if this is related to #4? I have some ideas on how to fix this but I need to experiment some more.

**Comment by theamazingfedex** [comment] 2016-04-05 18:40
Hmm, at first glance, it seems different, as refreshing the chrome page doesn't accomplish anything.

**Comment by euclio** [comment] 2016-04-05 20:00
Weird. I'll reopen this in hopes that I can get it to happen for me.

**Comment by theamazingfedex** [comment] 2016-04-05 22:21
Next time I get it to reproduce, I'll see if I can get a screen-cap, and then I'll just dump any and every pertinent log I can find.

**Comment by euclio** [comment] 2017-04-10 15:49
By now I've completely written the server backend to be much simpler. I'm pretty confident that there are no more deadlocks, but feel free to reopen if you see this issue again!

**Closed by euclio** 2017-04-10 15:49 UTC
Labels: bug
