### ISSUE TITLE
Question: how to use pandoc to generate the markdown preview?

### ISSUE THREAD

**Issue by Alok** [euclio/vim-markdown-composer#21] opened 2016-11-14 00:52 UTC
I use pandoc's flavor of markdown, and not all its features render correctly in the preview. Is there a way to make pandoc the processor so it can generate the correct HTML?

**Comment by euclio** [comment] 2016-11-14 21:37
Hi @Alok, right now there is no way to make pandoc the markdown engine, but I may add the feature in the future as it has been requested a number of times.

**Comment by euclio** [comment] 2017-05-05 19:06
Closing as duplicate of #25.

**Closed by euclio** 2017-05-05 19:06 UTC
Labels: enhancement
