### ISSUE TITLE
Failure on Bigger Buffers

### ISSUE THREAD

**Issue by Cutuchiqueno** [euclio/vim-markdown-composer#15] opened 2016-05-17 20:28 UTC
With small markdown files I do not have any problems and the browser starts automatically with the preview. However, when I open longer files such as 5000+ words nothing happens.

When I try to open a preview automatically the following error message appears:

```
error caught in async handler '/home/cutuchiqueno/.vim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer:command:ComposerOpen []':
AttributeError("'NoneType' object has no attribute 'send'",)
Traceback (most recent call last):
File "/usr/lib/python3.5/site-packages/neovim/plugin/host.py", line 91, in _on_notification
handler(*args)
File "/usr/lib/python3.5/site-packages/neovim/plugin/host.py", line 160, in decoder
return fn(*walk(decode_if_bytes, args, decode))
File "/home/cutuchiqueno/.vim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 58, in composer_open
self.open_browser()
File "/home/cutuchiqueno/.vim/plugged/vim-markdown-composer/rplugin/python3/markdown_composer/__init__.py", line 49, in open_browser
self.client.send(msg)                                                                        
AttributeError: 'NoneType' object has no attribute 'send'
```

I am not quiet sure what causes. If it is really the size of the buffer or something else. How should I debug it?

**Comment by euclio** [comment] 2016-05-17 20:47
I have a theory that this might be caused by the (rather hacky) way I pass the server the initial markdown buffer to render. Can you check if you have any data in `/home/cutuchiqueno/.vim/plugged/vim-markdown-composer/log.log`?

**Comment by Cutuchiqueno** [comment] 2016-05-17 20:52
Unfortunately, this file does not exist in the plugin folder.

**Comment by euclio** [comment] 2016-05-17 21:00
Ok, I will try to reproduce.

**Comment by euclio** [comment] 2016-05-18 17:16
Having trouble reproducing. Could you upload a copy of a file that fails?

Also, if you want to try and get a log of the failure, you can try creating `/home/cutuchiqueno/.vim/plugged/vim-markdown-composer/config/log.toml` with the following contents:

```toml
refresh_rate = 5

[appender.file]
kind = "file"
path = "/home/cutuchiqueno/log.log"

[root]
level = "debug"
appenders = ["file"]
```

This will create `/home/cutuchiqueno/log.log`.

**Comment by Cutuchiqueno** [comment] 2016-05-19 08:22
I created the file you described above and the result seems quite mysterious for me. More precisely, on files which succeed the `log.log` file is created and obviously there are no issues mentioned in it.

When I open a file which does not succeed there is not even a `log.log` file created.

In both cases the `filetype=pandoc` markdown. The `log.log` file is also not created when I manually do `:ComposeStart` or `:ComposeOpen` in the not succeeding file.

I sent you the not succeeding file but did it privately to your e-mail since it is a journal article which has not being published until now.

**Comment by euclio** [comment] 2016-05-23 20:41
Which other plugins do you have activated? If the `filetype` is not detected as markdown, then the server will not start. Does it work if you set your filetype to `markdown.pandoc`?

**Comment by Cutuchiqueno** [comment] 2016-05-24 11:49
I did some tests following yor suggestion:
`test.md` : succeeded
`test.pandoc` : does not work automatically, but manually by using `ComposerOpen` or `ComposerStart`
`BIG_EXMPL_FILE.md` does not work and throws the exception I posted before
`BIG_EXMPL_FILE.pandoc` does not work and throws the exception I posted before`

`test.EXT` just has a view lines of markdown

**Comment by euclio** [comment] 2016-05-24 14:48
Hm, interesting. Thanks for the additional info.

**Comment by euclio** [comment] 2016-05-31 17:10
Note on progress: I believe I have a fix for this, but I'm going to batch it with some other fixes (particularly #4).

**Comment by euclio** [comment] 2016-08-06 02:32
Hm, I was hoping that my last commit would fix this, but it doesn't :( I think I might be overflowing the OS pipe buffer.

**Comment by Cutuchiqueno** [comment] 2016-08-16 12:08
thanks for keeping me updated

**Comment by euclio** [comment] 2016-12-29 23:42
@Cutuchiqueno This should be fixed in the latest version.

**Closed** 2016-12-29 23:42 UTC
Labels: bug
