### ISSUE TITLE
Server doesn't autostart

### ISSUE THREAD

**Issue by nimakro** [euclio/vim-markdown-composer#19] opened 2016-08-18 18:33 UTC
Hey there,
I have the following setup in my nvim setup.
`let g:markdown_composer_open_browser = 0`
`let g:markdown_composer_autostart = 1`
- Then if I open a markdown file and have a chromium instance running.
- And run `:ComposerOpen`

Expected behavior:
- Server ist started as soon as I open the markdown file.
- Markdown preview will be opened in a chromium tab.

Actuall behavior:
- The following error message occur's.
  ![image](https://cloud.githubusercontent.com/assets/21091608/17785595/b017baf4-6581-11e6-8292-289a0e057c05.png)
- If I run `:ComposerStart` and then `:ComposerOpen` everything works fine, so it seems that the server is not automatically started even though I have the variable set explicitly?

Regards 
Micah

**Comment by miotatsu** [comment] 2016-10-04 04:40
I'm not sure if this is the same issue, but it also does not autostart for me. I am on arch linux and have this plugin installed with Plug, I'm using neovim. If I open a markdown document, nothing special happens. If I execute :ComposerStart then the preview opens in my browser and it updates live as I edit the document. Note also that :ComposerStart does not autocomplete (nor do any of the other commands this plugin has), but they do after I've executed one. This is the only plugin that I have this problem with.

**Comment by euclio** [comment] 2016-10-18 20:29
I am unable to reproduce the issue. Your sequence of steps works as expected for me.

Can you try `cargo run --release` in the plugin directory and see if the client starts properly?

**Comment by miotatsu** [comment] 2016-10-18 20:45
`cargo run --release` in the plugin directory appears to start the client without issue for me.

**Comment by euclio** [comment] 2016-12-29 23:43
This should be fixed in the latest version, as the Python dependency has been dropped.

**Closed by euclio** 2016-12-29 23:43 UTC
